Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !ImportValue eks-cluster-ClusterName
      InstanceTypes:
        - t2.micro
      NodegroupName: eks-nodegroup
      NodeRole: !ImportValue eks-role-NODE-RoleArn
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 2
      Subnets: !Split [",", !ImportValue eks-vpc-PUB-SUBNETS]
