apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 80
  selector:
    name: hello-app
    version: TAGVERSION
  type: LoadBalancer
