apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    name: hello-app
    version: "TAGVERSION"
  type: LoadBalancer
